name: Deploy  #name of the workflow

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # checkout the code from the repository

    - name: Build Docker image 
      run: docker build -t chiragrathod25/videonest-backend .

    - name: Login to Docker Hub
      run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin # it will got the credentials from github action secrets
    
    - name: Push Docker image to Docker Hub
      run: docker push chiragrathod25/videonest-backend:latest